/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code.addressbook;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Faisal
 */
public class search extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    DbUtil dbUtil;
    String bgs;
    /**
     * Creates new form search
     */
    String value;
    int index;

    public search() {
        initComponents();
        dbUtil = new DbUtil();
        refresh_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        biComboBox = new javax.swing.JComboBox<>();
        search1 = new javax.swing.JTextField();
        search_cr1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        dobsr = new com.toedter.calendar.JDateChooser();
        search_cr2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        biComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        biComboBox3 = new javax.swing.JComboBox<>();
        search2 = new javax.swing.JTextField();
        search3 = new javax.swing.JTextField();
        search_cr3 = new javax.swing.JButton();
        search_cr4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_tbl = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        vl = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        edit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        save_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        select = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        middle_name = new javax.swing.JTextField();
        first_name = new javax.swing.JTextField();
        last_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nid = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        bg = new javax.swing.JComboBox<>();
        tel = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sbg = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        ph2 = new javax.swing.JTextField();
        ph3 = new javax.swing.JTextField();
        email2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        dv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ds = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        up = new javax.swing.JTextField();
        po = new javax.swing.JTextField();
        pc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hm = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        dv2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ds2 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        up2 = new javax.swing.JTextField();
        po2 = new javax.swing.JTextField();
        pc2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hm2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><p><font size=\"8\">SEARCH CONTACTS | </font> advanced search contacts here.</p></html>");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel1.setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search By Basic Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        biComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Name", "District", "Country", "Blood Group" }));

        search_cr1.setText("SEARCH");
        search_cr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cr1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_cr1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(search_cr1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search By Date Of Birth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        dobsr.setDateFormatString("dd MMMM, YYYY");

        search_cr2.setText("SEARCH");
        search_cr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cr2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel5.setText("Choose");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(search_cr2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dobsr, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dobsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(search_cr2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search by Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        biComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Division", "District", "Upozilla", "Post Office", "Post Code" }));

        jLabel2.setText("Current Address");

        jLabel3.setText("Permanent Address");

        biComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Division", "District", "Upozilla", "Post Office", "Post Code" }));

        search_cr3.setText("SEARCH");
        search_cr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cr3ActionPerformed(evt);
            }
        });

        search_cr4.setText("SEARCH");
        search_cr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_cr4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(biComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(search_cr3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(search2)
                                    .addComponent(search3))
                                .addContainerGap())))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(search_cr4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_cr3)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(biComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_cr4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTACTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        data_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        data_tbl.setRowHeight(20);
        data_tbl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        data_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data_tbl);

        jButton5.setText("REFRESH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        vl.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        vl.setForeground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACTIONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        edit_btn.setText("EDIT    ");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("DELETE  ");
        delete_btn.setEnabled(false);
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        save_btn.setText("SAVE    ");
        save_btn.setEnabled(false);
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        exit_btn.setText("EXIT");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });

        back_btn.setText("BACK");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        select.setText("SELECT");
        select.setEnabled(false);

        cancel_btn.setText("CANCEL  ");
        cancel_btn.setEnabled(false);
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(save_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(edit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(select, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110)
                .addComponent(select, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14), new java.awt.Color(0, 153, 153))); // NOI18N

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        middle_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        first_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        last_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name:");

        dob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        dob.setDateFormatString("dd MMMM, YYYY");
        dob.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dobPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Date Of Birth :");

        jLabel25.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel25.setText("Choose Date");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Country :");

        country.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("E mail:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("NID:");

        nid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Blood Group:");

        bg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        bg.setEnabled(false);
        bg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgActionPerformed(evt);
            }
        });

        tel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Phone No:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Telephone :");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(first_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(middle_name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(last_name)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel6)
                        .addContainerGap())
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7))
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                            .addComponent(country)))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sbg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bg, 0, 146, Short.MAX_VALUE)
                                .addGap(111, 111, 111)))
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tel, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                                    .addComponent(nid))
                                .addGap(25, 25, 25))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)))
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sbg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel29)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General Info", jPanel11);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        ph2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ph3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        email2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Additional Email:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Additional Phone No :");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ph2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addComponent(ph3))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ph3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Additional Contact Info", jPanel10);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Division :");

        dv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("District :");

        ds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Home Address :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Upozilla: ");

        up.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        po.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Post Office: ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Post Code: ");

        hm.setColumns(20);
        hm.setRows(5);
        jScrollPane3.setViewportView(hm);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dv, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(up)
                    .addComponent(po)
                    .addComponent(pc))
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ds)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dv)
                    .addComponent(jLabel13)
                    .addComponent(ds))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(up)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(po)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pc)
                            .addComponent(jLabel17)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Present Address", jPanel8);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Division :");

        dv2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("District :");

        ds2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Home Address :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Upozilla: ");

        up2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        po2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pc2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Post Office: ");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Post Code: ");

        hm2.setColumns(20);
        hm2.setRows(5);
        jScrollPane2.setViewportView(hm2);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dv2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(up2)
                    .addComponent(po2)
                    .addComponent(pc2))
                .addGap(23, 23, 23)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(ds2)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(dv2)
                    .addComponent(jLabel19)
                    .addComponent(ds2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(up2)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(po2)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pc2)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Permanent Address", jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dobPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dobPropertyChange
        // TODO add your handling code here:
        /* value = SearchComboBox.getSelectedItem().toString();
        if (value == "Date Of Birth") {
            search.setText(((JTextField) dob.getDateEditor().getUiComponent()).getText());
        } else {
            search.setText("");
        }*/
    }//GEN-LAST:event_dobPropertyChange
    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    private void refresh_table() {

        try {
            con = dbUtil.getConnection();
            Statement stmt = con.createStatement();
            String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', Phone FROM info";
            rs = stmt.executeQuery(SQL);
            data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        } finally {
            dbUtil.closeConnection();
        }
    }

    private void search_cr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cr1ActionPerformed
        // TODO add your handling code here:
        value = biComboBox.getSelectedItem().toString();
        vl.setText("Search By Basic Info");
        if (value == "SELECT") {
            JOptionPane.showMessageDialog(null, "Select a field first.", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            /*if (value == "Name") {
            try {
                con = dbUtil.getConnection();

                Statement stmt = con.createStatement();
                String tmp1 = search1.getText();
                String SQL = "SELECT  USER_ID, FirstName, MidleName, LastName, Phone FROM info WHERE MidleName='" + tmp1 + "'";
                rs = stmt.executeQuery(SQL);

                data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException err) {

            } finally {
                dbUtil.closeConnection();
            }
        }*/
            if (value == "Name") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search1.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', Phone FROM info WHERE FirstName='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
                int row = data_tbl.getRowCount();
                if (row == 0) {
                    try {
                        con = dbUtil.getConnection();
                        Statement stmt = con.createStatement();
                        String tmp = search1.getText();
                        String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', Phone FROM info WHERE LastName='" + tmp + "'";
                        rs = stmt.executeQuery(SQL);

                        data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                    } catch (SQLException err) {

                    } finally {
                        dbUtil.closeConnection();
                    }
                }
            }

            if (value == "District") {

                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search1.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', District, Phone FROM info WHERE District='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }

            if (value == "Country") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search1.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', Country, Phone FROM info WHERE Country='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }

            if (value == "Blood Group") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search1.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', BloodGroup, Phone FROM info WHERE BloodGroup='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }
            int row = data_tbl.getRowCount();
            if (row == 0) {
                JOptionPane.showMessageDialog(null, "Not Found! ", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_search_cr1ActionPerformed

    private void search_cr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cr2ActionPerformed
        // TODO add your handling code here:
        String tmp = (String) ((JTextField) dobsr.getDateEditor().getUiComponent()).getText();
        vl.setText("Search By Date Of Birth");
        if (tmp.equals("")) {
            JOptionPane.showMessageDialog(null, "Choose a date first.", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                con = dbUtil.getConnection();

                Statement stmt = con.createStatement();
                String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', DateOfBirth as 'Date of  Birth', Phone as 'Phone' FROM info WHERE DateOfBirth='" + tmp + "'";
                rs = stmt.executeQuery(SQL);

                data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

            } catch (SQLException err) {

            } finally {
                dbUtil.closeConnection();
            }
            int row = data_tbl.getRowCount();
            if (row == 0) {
                JOptionPane.showMessageDialog(null, "Not Found! ", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_search_cr2ActionPerformed

    private void search_cr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cr3ActionPerformed
        // TODO add your handling code here:
        value = biComboBox2.getSelectedItem().toString();
        vl.setText("Search by Present Address");
        if (value == "SELECT") {
            JOptionPane.showMessageDialog(null, "Select a field first.", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (value == "Division") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search2.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name',Division, Phone FROM info WHERE Division='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }

            }

            if (value == "District") {

                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search2.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', District, Phone FROM info WHERE District='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }

            if (value == "Upozilla") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search2.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', Upozilla, Phone FROM info WHERE Upozilla='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }

            if (value == "Post Office") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search2.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name',PostOffice, PostCode FROM info WHERE PostOffice='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }

            if (value == "PostCode") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search2.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', PostCode, PostOffice FROM info WHERE PostCode='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }
            int row = data_tbl.getRowCount();
            if (row == 0) {
                JOptionPane.showMessageDialog(null, "Not Found! ", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }


    }//GEN-LAST:event_search_cr3ActionPerformed

    private void search_cr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_cr4ActionPerformed
        // TODO add your handling code here:
        value = biComboBox3.getSelectedItem().toString();
        vl.setText("Search by Permanent Address");
        if (value == "SELECT") {
            JOptionPane.showMessageDialog(null, "Select a field first.", "Info", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (value == "Division") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search3.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', Division2 as 'Division' FROM info WHERE Division2='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }

            }

            if (value == "District") {

                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search3.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', District2 as 'District', Phone FROM info WHERE District2='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }

            if (value == "Upozilla") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search3.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', Upozilla2 as 'Upozilla', Phone FROM info WHERE Upozilla2='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }

            if (value == "Post Office") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search3.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name', PostOffice2 as 'Post Office', PostCode2 as 'Post Code' FROM info WHERE PostOffice2='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }

            if (value == "Post Code") {
                try {
                    con = dbUtil.getConnection();

                    Statement stmt = con.createStatement();
                    String tmp = search3.getText();
                    String SQL = "SELECT  USER_ID as 'INDEX',FirstName as 'First Name',MidleName as 'Midle Name', LastName as 'Last Name',PostOffice2 as 'Post Office', PostCode2 as 'Post Code' FROM info WHERE PostCode2='" + tmp + "'";
                    rs = stmt.executeQuery(SQL);

                    data_tbl.setModel(DbUtils.resultSetToTableModel(rs));

                } catch (SQLException err) {

                } finally {
                    dbUtil.closeConnection();
                }
            }
            int row = data_tbl.getRowCount();
            if (row == 0) {
                JOptionPane.showMessageDialog(null, "Not Found! ", "Info", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_search_cr4ActionPerformed

    private void data_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_tblMouseClicked
        // TODO add your handling code here:
        int row = data_tbl.getSelectedRow();
        String click = (data_tbl.getValueAt(row, 0).toString());
        /*try {
            con = dbUtil.getConnection();
            
            String SQL = "SELECT Image FROM info WHERE USER_ID='" + click + "'";
            Statement stmt = con.createStatement();

            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                
                
             byte[]imagedata = rs.getBytes("Image");
                img = new ImageIcon(imagedata);
                img_show.setIcon(img);
            }

        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        } finally {
            dbUtil.closeConnection();
        }*/

        try {
            con = dbUtil.getConnection();

            String SQL = "SELECT * FROM info WHERE USER_ID='" + click + "'";
            Statement stmt = con.createStatement();

            rs = stmt.executeQuery(SQL);
            while (rs.next()) {
                String f1 = rs.getString("FirstName");
                first_name.setText(f1);
                String f2 = rs.getString("MidleName");
                middle_name.setText(f2);
                String f3 = rs.getString("LastName");
                last_name.setText(f3);
                String f4 = rs.getString("DateOfBirth");
                ((JTextField) dob.getDateEditor().getUiComponent()).setText(f4);
                String f5 = rs.getString("Country");
                country.setText(f5);
                String f6 = rs.getString("Phone");
                phone.setText(f6);
                String f7 = rs.getString("Telephone");
                tel.setText(f7);
                String f8 = rs.getString("Phone1");
                ph2.setText(f8);
                String f9 = rs.getString("Phone2");
                ph3.setText(f9);
                String f10 = rs.getString("Email");
                email.setText(f10);
                String f11 = rs.getString("AdditionalEmail");
                email2.setText(f11);
                String f12 = rs.getString("Division");
                dv.setText(f12);
                String f13 = rs.getString("District");
                ds.setText(f13);
                String f14 = rs.getString("Upozilla");
                up.setText(f14);
                String f15 = rs.getString("PostOffice");
                po.setText(f15);
                String f16 = rs.getString("PostCode");
                pc.setText(f16);
                String f17 = rs.getString("Home");
                hm.setText(f17);
                String f18 = rs.getString("Division2");
                dv2.setText(f18);
                String f19 = rs.getString("District2");
                ds2.setText(f19);
                String f20 = rs.getString("Upozilla2");
                up2.setText(f20);
                String f21 = rs.getString("PostOffice2");
                po2.setText(f21);
                String f22 = rs.getString("PostCode2");
                pc2.setText(f22);
                String f23 = rs.getString("Home2");
                hm2.setText(f23);
                String f25 = rs.getString("NID");
                nid.setText(f25);
                String f26 = rs.getString("BloodGroup");
                sbg.setText(f26);
                bg.setSelectedItem("SELECT");
            }

        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        } finally {
            dbUtil.closeConnection();
        }
        save_btn.setEnabled(false);
        cancel_btn.setEnabled(false);
        edit_btn.setEnabled(true);
        delete_btn.setEnabled(false);
        bg.setEnabled(false);
    }//GEN-LAST:event_data_tblMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        refresh_table();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        close();
        addressbookUI input = new addressbookUI();
        input.setVisible(false);
    }//GEN-LAST:event_back_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you want to exit the app ?", "Exit Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exit_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you want to delete this record ?", "DELETE Confirmation", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            int row = data_tbl.getSelectedRow();
            index = Integer.parseInt(data_tbl.getValueAt(row, 0).toString());
            try {
                con = dbUtil.getConnection();
                String SQL = "DELETE FROM info WHERE USER_ID='" + index + "'";
                Statement stmt = con.createStatement();
                stmt.execute(SQL);
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            } finally {
                dbUtil.closeConnection();
            }
            int count = 0;
            int i, j;
            try {
                con = dbUtil.getConnection();

                String SQL = "SELECT COUNT(*) FROM info";
                Statement stmt = con.createStatement();

                rs = stmt.executeQuery(SQL);
                while (rs.next()) {
                    count = rs.getInt(1);

                }
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            } finally {
                dbUtil.closeConnection();
            }
            int id = index + 1;
            for (i = id; i <= count + 1; i++) {
                j = i - 1;
                System.out.println(i);
                try {
                    String SQL = "UPDATE info SET USER_ID=? WHERE USER_ID='" + i + "'";
                    con = dbUtil.getConnection();
                    pst = con.prepareStatement(SQL);
                    pst.setInt(1, j);
                    pst.executeUpdate();

                    System.out.println("jk");
                } catch (SQLException err) {
                    JOptionPane.showMessageDialog(null, err.getMessage());
                } finally {
                    dbUtil.closeConnection();
                }
            }
            try {
                String SQL = "UPDATE SQLITE_SEQUENCE SET seq = 0 WHERE NAME ='info'";
                con = dbUtil.getConnection();
                pst = con.prepareStatement(SQL);
                pst.executeUpdate();
            } catch (SQLException err) {
                JOptionPane.showMessageDialog(null, err.getMessage());
            } finally {
                dbUtil.closeConnection();
            }
            JOptionPane.showMessageDialog(null, "Deleted. ", "Info", JOptionPane.INFORMATION_MESSAGE);
            refresh_table();
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
        save_btn.setEnabled(true);
        cancel_btn.setEnabled(true);
        edit_btn.setEnabled(false);
        delete_btn.setEnabled(true);
        bg.setEnabled(true);
    }//GEN-LAST:event_edit_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        save_btn.setEnabled(false);
        cancel_btn.setEnabled(false);
        edit_btn.setEnabled(true);
        delete_btn.setEnabled(false);
        bg.setEnabled(false);
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you want to update this record ?", "Update", JOptionPane.YES_NO_OPTION);
        if (p == 0) {

            try {
                int row = data_tbl.getSelectedRow();
                String index = (data_tbl.getValueAt(row, 0).toString());
                String SQL = "UPDATE info SET FirstName=?, MidleName=?, LastName=?, DateOfBirth=?, Country=?, Email=?, AdditionalEmail=?, Phone=?, Phone1=?, Phone2=?, Telephone=?, Division=?, District=?, Upozilla=?, PostOffice=?, PostCode=?, Home=?, Division2=?, District2=?, Upozilla2=?, PostOffice2=?, PostCode2=?, Home2=?, NID=?, BloodGroup=? WHERE USER_ID='" + index + "'";
                con = dbUtil.getConnection();
                pst = con.prepareStatement(SQL);
                pst.setString(1, first_name.getText());
                pst.setString(2, middle_name.getText());
                pst.setString(3, last_name.getText());
                pst.setString(4, ((JTextField) dob.getDateEditor().getUiComponent()).getText());
                pst.setString(5, country.getText());
                pst.setString(6, email.getText());
                pst.setString(7, email2.getText());
                pst.setString(8, phone.getText());
                pst.setString(9, ph2.getText());
                pst.setString(10, ph3.getText());
                pst.setString(11, tel.getText());
                pst.setString(12, dv.getText());
                pst.setString(13, ds.getText());
                pst.setString(14, up.getText());
                pst.setString(15, po.getText());
                pst.setString(16, pc.getText());
                pst.setString(17, hm.getText());
                pst.setString(18, dv2.getText());
                pst.setString(19, ds2.getText());
                pst.setString(20, up2.getText());
                pst.setString(21, po2.getText());
                pst.setString(22, pc2.getText());
                pst.setString(23, hm2.getText());
                pst.setString(24, nid.getText());
                if (bg.getSelectedItem().toString().equals("SELECT")) {
                    bgs = sbg.getText();
                    pst.setString(25, bgs);
                } else {
                    bgs = bg.getSelectedItem().toString();
                    pst.setString(25, bgs);
                }

                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Updated Successfully ", "Info", JOptionPane.INFORMATION_MESSAGE);
                refresh_table();

            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Record Not Updated Successfully Due to " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                dbUtil.closeConnection();
            }
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void bgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JComboBox<String> bg;
    private javax.swing.JComboBox<String> biComboBox;
    private javax.swing.JComboBox<String> biComboBox2;
    private javax.swing.JComboBox<String> biComboBox3;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JTextField country;
    private javax.swing.JTable data_tbl;
    private javax.swing.JButton delete_btn;
    private com.toedter.calendar.JDateChooser dob;
    private com.toedter.calendar.JDateChooser dobsr;
    private javax.swing.JTextField ds;
    private javax.swing.JTextField ds2;
    private javax.swing.JTextField dv;
    private javax.swing.JTextField dv2;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email2;
    private javax.swing.JButton exit_btn;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextArea hm;
    private javax.swing.JTextArea hm2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField middle_name;
    private javax.swing.JTextField nid;
    private javax.swing.JTextField pc;
    private javax.swing.JTextField pc2;
    private javax.swing.JTextField ph2;
    private javax.swing.JTextField ph3;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField po;
    private javax.swing.JTextField po2;
    private javax.swing.JButton save_btn;
    private javax.swing.JLabel sbg;
    private javax.swing.JTextField search1;
    private javax.swing.JTextField search2;
    private javax.swing.JTextField search3;
    private javax.swing.JButton search_cr1;
    private javax.swing.JButton search_cr2;
    private javax.swing.JButton search_cr3;
    private javax.swing.JButton search_cr4;
    private javax.swing.JButton select;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField up;
    private javax.swing.JTextField up2;
    private javax.swing.JLabel vl;
    // End of variables declaration//GEN-END:variables

}
